version: '3'
services:
    go:
        build:
            context: ./backend
            dockerfile: Dockerfile.local
        volumes:
            - ./backend:/go/src/backend
        working_dir: /go/src/backend
        environment:
            TZ: Asia/Tokyo
        ports:
            - 8080:8080
            - 2345:2345
        security_opt: 
            - apparmor:unconfined
        cap_add: 
            - SYS_PTRACE

    next:
      image: node:15.0.1
      volumes:
        - ./frontend:/home/app/frontend
        - node_modules_volume:/home/app/frontend/node_modules
      ports:
        - 3000:3000
      working_dir: /home/app/frontend
      command: [bash, -c, yarn upgrade --no-progress --network-timeout 1000000 && yarn run dev]

    mysql:
        build: ./mysql
        environment:
            TZ: Asia/Tokyo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend
        ports:
            - 13306:3306
        volumes:
            - mysql_volume:/var/lib/mysql
    
volumes:
    mysql_volume:
    node_modules_volume:
